### ISSUE TITLE
Unidentified items show all their enchantments when expanded

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/d35e-loot-sheet-npc#19] opened 2021-03-16 22:18 UTC
If you have an unidentified item then when you click on it in the loot sheet it shows all its enchantments.  The enchantments are also showing up as clickable actions which then throws a warning when clicked on
![image](https://user-images.githubusercontent.com/22633854/111387095-1b427c80-86a5-11eb-9113-e54a32495503.png)
![image](https://user-images.githubusercontent.com/22633854/111387190-3ca36880-86a5-11eb-91c0-7356891c5af2.png)

**Comment by Rughalt** [comment] 2021-04-03 08:36
Caused by problem in upstream - should be fixed now.

**Closed by Rughalt** 2021-04-03 08:36 UTC
Labels: system
